// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0oPaF47GN-3HooV9wyFJN65eKIM-5L38',
    appId: '1:966568386746:web:366e47dcbbec144a652283',
    messagingSenderId: '966568386746',
    projectId: 'tilda-c0030',
    authDomain: 'tilda-c0030.firebaseapp.com',
    storageBucket: 'tilda-c0030.firebasestorage.app',
    measurementId: 'G-R9YN6828G6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDbhURwYq9pQ2LP88t20szhiiw_ioXaLk',
    appId: '1:966568386746:android:34b77e11e0fc2e07652283',
    messagingSenderId: '966568386746',
    projectId: 'tilda-c0030',
    storageBucket: 'tilda-c0030.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmiQQJR-Am4bG_8wOX9gr7rWtygQXYzgg',
    appId: '1:966568386746:ios:1a1f862a615eb7fd652283',
    messagingSenderId: '966568386746',
    projectId: 'tilda-c0030',
    storageBucket: 'tilda-c0030.firebasestorage.app',
    iosBundleId: 'com.example.tildaRecipes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmiQQJR-Am4bG_8wOX9gr7rWtygQXYzgg',
    appId: '1:966568386746:ios:1a1f862a615eb7fd652283',
    messagingSenderId: '966568386746',
    projectId: 'tilda-c0030',
    storageBucket: 'tilda-c0030.firebasestorage.app',
    iosBundleId: 'com.example.tildaRecipes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0oPaF47GN-3HooV9wyFJN65eKIM-5L38',
    appId: '1:966568386746:web:c2d7400e765ca329652283',
    messagingSenderId: '966568386746',
    projectId: 'tilda-c0030',
    authDomain: 'tilda-c0030.firebaseapp.com',
    storageBucket: 'tilda-c0030.firebasestorage.app',
    measurementId: 'G-3JXVETYHRE',
  );

}